### ISSUE TITLE
การส่ง-รับภาพ

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/HCI-UNIT#1]
- [x] ระบบสามารถส่งภาพ Stereoscopic จาก AVATAR มายัง OPERATOR ได้
- [x] ภาพมีความเร็วไม่ต่ำกว่า 24 FPS

**Comment by Cluster-APX** [comment]
ทดสอบรับ-ส่งในเครื่องเดียวกัน
- Sender ส่งได้ > 30 FPS
- Receiver รับได้ 14 FPS

**Comment by kong4580** [comment]
ิ

> ทดสอบรับ-ส่งในเครื่องเดียวกัน
> 
> * Sender ส่งได้ > 30 FPS
> * Receiver รับได้ 14 FPS

อันนี้คือผ่าน super res รึยังครับ

**Comment by Cluster-APX** [comment]
> ิ
> 
> > ทดสอบรับ-ส่งในเครื่องเดียวกัน
> > 
> > * Sender ส่งได้ > 30 FPS
> > * Receiver รับได้ 14 FPS
> 
> อันนี้คือผ่าน super res รึยังครับ

ไม่จำเป็น ถ้าผ่าน Super RES แล้วได้อย่างที่ว่าจะดีมาาก

**Comment by Cluster-APX** [comment]
เท่าที่ลองดูโดย Source Code เดิม คือถ้าใช้เครื่องแรงขึ้นมันก็จะเร็วขึ้น!

**Comment by Cluster-APX** [comment]
- ใช้กล้อง ZED mini
- Resolution = 2560x720
- ปรับ Quality เหลือประมาณ 10
