### ISSUE TITLE
UX/UI : 1

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/HCI-UNIT#19]
`15 Oct 2020`

- จด Function/Menu ที่ Operator เข้าถึงได้ https://github.com/XPrize-Perception-Team/HCI-UNIT.UX-UI/issues/5
- สรุปพร้อมเปรียบเทียบ solution ต่าง ๆ เป็นตาราง https://github.com/XPrize-Perception-Team/HCI-UNIT.UX-UI/issues/4

**Comment by KRIneTic-39** [comment]
อาทิตย์นี้ทำในส่วน : สรุปพร้อมเปรียบเทียบ solution ต่าง ๆ เป็นตาราง XPrize-Perception-Team/HCI-UNIT.UX-UI#4
อาทิตย์หน้าจะทำในส่วน : สอบถามความต้องการเพิ่มเติมแล้ว จด Function/Menu ที่ Operator เข้าถึงได้ XPrize-Perception-Team/HCI-UNIT.UX-UI#5
