### ISSUE TITLE
3D Sound : 1

### ISSUE THREAD

**Issue by Cluster-APX** [XPrize-Perception-Team/HCI-UNIT#20]
`15 Oct 2020`

- จำลองส่งเสียงจาก AVATAR ด้วยไฟล์เสียง
- ยังไม่ต้องใช้ Unity

https://github.com/XPrize-Perception-Team/HCI-UNIT.3D-Sound/issues/1

**Comment by RyuuseiX** [comment]
ทำแล้วแต่ยังไม่เสร็จ ส่งไฟล์เสียง 8ch แล้วแต่เสียงเน่า ต้องไปปรับ parameter ใหม่ สามารถบังคับให้ 8ch ออกมา 2ch ได้ ทั้งเล่นพร้อมกันทั้งเลือก 2ch คิดว่าจะเปลี่ยนไปเทสกับไมค์แทน

**Comment by Cluster-APX** [comment]
ไม่ต้องจำลองแล้ว ให้ใช้ Hardware จริงไปเลย
