### ISSUE TITLE
UX/UI : 2

### ISSUE THREAD

**Issue by PeaceChanpornpakdee** [XPrize-Perception-Team/HCI-UNIT#24]
`22/10/63`

จด Function/Menu ที่ Operator เข้าถึงได้ (ทำต่อจากงานสัปดาห์ที่แล้ว) และเรียบเรียงเป็น user story
XPrize-Perception-Team/HCI-UNIT.UX-UI#5
https://github.com/XPrize-Perception-Team/HCI-UNIT/projects/3#card-46979711

**Comment by Cluster-APX** [comment]
ไฟล์ Power Point โพสไว้ใน GDrive

@PeaceChanpornpakdee เอาไฟล์ไปอัพโหลดไว้ที่ ms teams ด้วย
