### ISSUE TITLE
UX/UI : Demo in Unity

### ISSUE THREAD

**Issue by PeaceChanpornpakdee** [XPrize-Perception-Team/HCI-UNIT#28]
ทำ Demo ของ UI ที่ออกแบบไว้ ให้อยู่บน Unity

**Comment by Cluster-APX** [comment]
กฤตร่าง UI เบื้องต้นแล้ว (ยังไม่เสร็จ) ``ทำการเคลื่อนที่ในUnityให้ชนสิ่งของแต่ยังไม่สามารถทำ Pop up
หน้าต่างเมนูได้``
