### ISSUE TITLE
3D SOUND : ซื้อของ 1 

### ISSUE THREAD

**Issue by RyuuseiX** [XPrize-Perception-Team/HCI-UNIT#32]
ซื้อ Logitech 981-000536 G430 7.1 Gaming Headset with Mic 
- https://www.amazon.com/Logitech-G430-Headphone-Cable-Sports-Performance/dp/B00CQ35C1Q?tag=musiccritic-search-20

หรือไมค์อื่นๆที่ไม่เป็น wireless และมีไมค์ในตัว ใน list นี้
- https://musiccritic.com/equipment/headphones/best-surround-sound-headphones/

**Comment by Cluster-APX** [comment]
เอาข้อมูลไปใส่ใน repo ของตัวเอง https://github.com/XPrize-Perception-Team/HCI-UNIT.3D-Sound/projects/1
